### ISSUE TITLE
License

### ISSUE THREAD

**Issue by turbomaze** [wybiral/python-musical#5]
Hello,

I'd like to use this code in a project of mine (non-commercial and will be OSS), but there doesn't seem to be a license file. Could you add one? Is this URL correct in that this is released under LGPL? https://code.google.com/archive/p/python-musical/

Anthony

**Comment by wybiral** [comment]
Wow, I neglected this project quite a bit. I've added the license as MIT since it's commonly used in these kinds of situations but my own opinion on the matter is:
> Do whatever you want, don't blame me if something breaks, and credit is cool but Bowie and Queen didn't make that big of a deal about Vanilla Ice ripping off Under Pressure and neither will I if you rip off this code.
