### ISSUE TITLE
Remove SciPy

### ISSUE THREAD

**Issue by wybiral** [wybiral/python-musical#8]
Requiring SciPy just for from ```scipy.signal.waveforms``` is overkill. It would make much more sense to just implement square and sawtooth waves using plain NumPy methods.

**Comment by wgaylord** [comment]
Any progress on this?

**Comment by wybiral** [comment]
I wrote the helper functions but never merged them into this repo. Thanks for reminding me!

https://github.com/wybiral/python-musical/commit/216d2211f06746d540e048be795947a33ddff747

If you're interested in contributing to the wave source part of the code though, it still needs a triangle wave source.
